service: demo-project

plugins:
  - serverless-python-requirements
  - serverless-dotenv-plugin


provider:
  name: aws
  runtime: python3.8
  stage: ${self:custom.stage}
  deploymentBucket:
    name: demo-deployments-${self:custom.stage}
    serverSideEncryption: aws:kms
    SSEKMSKeyId: "TestKeyId"
  role: "TestRole"


package:
  individually: true
  exclude:
    - /**
    - "*/**"
    - node_modules/**


functions:
  # Event Service Functions
  demo-lambda: ${file(./demo-repository/demo-lambda/function.yml)}

frameworkVersion: ">=1.2.0 <2.0.0"
custom:
  stage: ${opt:stage, "dev"}
  version: ${env:BUILD_VERSION, env:RV, self:custom.stage}